#!/bin/bash

echo "🔧 Fixing Sitemap - Adding Blog URLs"
echo "======================================"
echo ""
echo "PROBLEM: Sitemap doesn't include blog posts"
echo "SOLUTION: Rebuild frontend on Server 3"
echo ""
echo "======================================"
echo "STEPS TO FIX:"
echo "======================================"
echo ""
echo "1. SSH into Server 3 (Load Balancer)"
echo "   ssh -i ~/Downloads/key2.pem ec2-user@65.2.142.131"
echo ""
echo "2. Navigate to project directory"
echo "   cd ~/opinion-poll"
echo ""
echo "3. Pull latest changes"
echo "   git pull origin main"
echo ""
echo "4. Install dependencies (if needed)"
echo "   npm install"
echo ""
echo "5. Rebuild the frontend"
echo "   npm run build"
echo ""
echo "6. Restart PM2"
echo "   pm2 restart frontend-server3"
echo ""
echo "7. Verify sitemap includes blog URLs"
echo "   curl https://opinionpoll.co.in/sitemap.xml | grep blog"
echo ""
echo "======================================"
echo "ALTERNATIVE: Quick Fix via SCP"
echo "======================================"
echo ""
echo "1. Build locally first"
echo "   npm run build"
echo ""
echo "2. Upload .next directory to Server 3"
echo "   scp -i ~/Downloads/key2.pem -r .next ec2-user@65.2.142.131:~/opinion-poll/"
echo ""
echo "3. Restart PM2 on Server 3"
echo "   ssh -i ~/Downloads/key2.pem ec2-user@65.2.142.131 'cd opinion-poll && pm2 restart frontend-server3'"
echo ""
echo "======================================"
echo "VERIFY THE FIX:"
echo "======================================"
echo ""
echo "1. Check sitemap has blog URLs:"
echo "   curl https://opinionpoll.co.in/sitemap.xml | grep -c blog"
echo "   (Should show at least 6 - one /blog page + 5 blog posts)"
echo ""
echo "2. Resubmit sitemap to Google Search Console:"
echo "   - Go to: https://search.google.com/search-console"
echo "   - Click 'Sitemaps'"
echo "   - Remove old sitemap.xml"
echo "   - Add sitemap.xml again"
echo "   - Wait for 'Success' status"
echo ""
echo "3. Request indexing for all blog URLs (as per submit-blog-urls.sh)"
echo ""
echo "======================================"
echo "WHY THIS HAPPENED:"
echo "======================================"
echo "The sitemap.ts file is correct and fetches blog posts dynamically."
echo "However, Server 3's .next build folder doesn't have the latest code."
echo "Rebuilding will regenerate sitemap with all blog URLs included."
echo ""
echo "======================================"
echo "EXPECTED RESULT:"
echo "======================================"
echo "After rebuild, sitemap.xml will include:"
echo "- https://opinionpoll.co.in/blog"
echo "- https://opinionpoll.co.in/blog/bihar-chunav-2025-sampurn-margdarshika"
echo "- https://opinionpoll.co.in/blog/bihar-political-parties-analysis"
echo "- https://opinionpoll.co.in/blog/matdan-prakriya-kaise-kare-vote"
echo "- https://opinionpoll.co.in/blog/bihar-chunav-2025-pramukh-mudde"
echo "- https://opinionpoll.co.in/blog/opinion-poll-kaise-kaam-karta-hai"
echo ""
echo "Google will then discover and index these pages!"
echo ""
