#!/bin/bash

# Generate list of all blog URLs for Google Search Console submission

echo "🔍 Generating blog URLs for indexing..."
echo ""
echo "Submit these URLs to Google Search Console:"
echo "https://search.google.com/search-console"
echo ""
echo "================================================"
echo "BLOG URLS TO INDEX"
echo "================================================"

# Main blog page
echo "https://opinionpoll.co.in/blog"

# Individual blog posts
echo "https://opinionpoll.co.in/blog/bihar-chunav-2025-sampurn-margdarshika"
echo "https://opinionpoll.co.in/blog/bihar-political-parties-analysis"
echo "https://opinionpoll.co.in/blog/matdan-prakriya-kaise-kare-vote"
echo "https://opinionpoll.co.in/blog/bihar-chunav-2025-pramukh-mudde"
echo "https://opinionpoll.co.in/blog/opinion-poll-kaise-kaam-karta-hai"

echo ""
echo "================================================"
echo "ISSUE: Crawled - Currently NOT Indexed"
echo "================================================"
echo "Your blog pages have been crawled but not indexed yet."
echo "This is NORMAL for new pages. Here's how to fix it:"
echo ""
echo "================================================"
echo "STEP-BY-STEP SOLUTION:"
echo "================================================"
echo ""
echo "STEP 1: Request Indexing for Each URL"
echo "--------------------------------------"
echo "1. Open: https://search.google.com/search-console"
echo "2. Select: opinionpoll.co.in"
echo "3. Click 'URL Inspection' tool (top search bar)"
echo "4. For EACH URL above:"
echo "   - Paste the URL"
echo "   - Press Enter and wait"
echo "   - Click 'REQUEST INDEXING' button"
echo "   - Wait 1-2 minutes for confirmation"
echo "   - Repeat for next URL"
echo ""
echo "STEP 2: Verify and Resubmit Sitemap"
echo "------------------------------------"
echo "1. Click 'Sitemaps' in left sidebar"
echo "2. Remove old sitemap if exists"
echo "3. Add new sitemap: sitemap.xml"
echo "4. Click 'SUBMIT'"
echo "5. Wait for 'Success' status"
echo ""
echo "STEP 3: Fix HTTP → HTTPS Redirect"
echo "----------------------------------"
echo "1. The redirect for http://opinionpoll.co.in/ is normal"
echo "2. Google prefers HTTPS - this is good!"
echo "3. Make sure all internal links use https://"
echo "4. Update canonical tags to HTTPS if needed"
echo ""
echo "================================================"
echo "EXPECTED TIMELINE:"
echo "================================================"
echo "- URL Inspection: Immediate (1-2 min per URL)"
echo "- Re-crawling: 1-3 days"
echo "- Indexing: 3-7 days after request"
echo "- Appearing in search: 7-14 days"
echo ""
echo "⚠️  'Crawled - not indexed' means Google found the page"
echo "    but hasn't added it to search results YET."
echo "    Requesting indexing will prioritize your pages!"
echo ""
echo "================================================"
echo "WHY PAGES AREN'T INDEXED YET:"
echo "================================================"
echo "✓ Pages are NEW (recently created)"
echo "✓ Google needs time to evaluate content quality"
echo "✓ Requesting indexing speeds up the process"
echo "✓ Your pages WILL be indexed after submitting"
echo ""
echo "================================================"
echo "VERIFY IT'S WORKING:"
echo "================================================"
echo "After 3-7 days, check:"
echo "1. Go to Coverage report in Search Console"
echo "2. Look for 'Valid' pages count increase"
echo "3. Test with: site:opinionpoll.co.in/blog in Google"
echo ""
